version: '3'

services:
  jaisoft-springboot-container:
    image: jpaliqubase-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/jaisoft-springboot-container
    ports:
      - "8080:8080"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: '0:0'
    container_name: MSSQLServer
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123@jkl#
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql